//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fitness.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Poseshenie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Poseshenie()
        {
            this.Zarplata_instruktoram = new HashSet<Zarplata_instruktoram>();
        }
    
        public int ID_poseshenia { get; set; }
        public int ID_abonement { get; set; }
        public int ID_zanjatia { get; set; }
    
        public virtual Abonement Abonement { get; set; }
        public virtual Raspisanie_zanjatij Raspisanie_zanjatij { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zarplata_instruktoram> Zarplata_instruktoram { get; set; }
    }
}
