//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fitness.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sotrudnik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sotrudnik()
        {
            this.Abonements = new HashSet<Abonement>();
            this.Raspisanie_zanjatij = new HashSet<Raspisanie_zanjatij>();
        }
    
        public int ID_sotrudnik { get; set; }
        public string FIO_sotrudnik { get; set; }
        public string Telephon { get; set; }
        public string Pasport { get; set; }
        public Nullable<int> ID_adress { get; set; }
        public Nullable<int> ID_dolgnost { get; set; }
        public string ID_Login { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Abonement> Abonements { get; set; }
        public virtual Adress Adress { get; set; }
        public virtual Dolgnost Dolgnost { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Raspisanie_zanjatij> Raspisanie_zanjatij { get; set; }
    }
}
