//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fitness.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zarplata_administratoram
    {
        public int ID_nachislenija { get; set; }
        public Nullable<int> ID_abonement { get; set; }
        public Nullable<double> Summa { get; set; }
    
        public virtual Abonement Abonement { get; set; }
    }
}
